version: '3.8'

services:
  api:
    build: ./
    command: gunicorn DjangoApp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/api/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks: 
      - django-app-net
  db:
    image: postgres:13.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    networks: 
      - django-app-net
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/api/staticfiles
    ports:
      - 1337:80
    depends_on: 
      - api
    networks: 
      - django-app-net

networks: 
  django-app-net:
    driver: bridge

volumes:
  postgres_data:
  static_volume: